package com.yss.db;

import java.util.Arrays;
import java.util.List;

public class Keys {

	public static List<String> T_PD_I_02_OUT_keys = Arrays.asList(new String[] {
			"APPSHEETSERIALNO", "TRANSACTIONCFMDATE", "RETURNCODE",
			"TRANSACTIONACCOUNTID", "DISTRIBUTORCODE", "BUSINESSCODE",
			"TAACCOUNTID", "MULTIACCTFLAG", "TASERIALNO", "TRANSACTIONDATE",
			"TRANSACTIONTIME", "BRANCHCODE", "FROMTAFLAG", "CERTIFICATETYPE",
			"CERTIFICATENO", "INVESTORNAME", "INDIVIDUALORINSTITUTION",
			"ACCOUNTABBR", "ACCOUNTCARDID", "REGIONCODE",
			"TARGETTRANSACTIONACCOUNTID", "NETNO", "SPECIFICATION",
			"CUSTOMERNO", "FROZENCAUSE", "FREEZINGDEADLINE", "ERRORDETAIL",
			"FSALE_ORG_ID", "ORGID" });
	public static List<String> T_PD_I_04_OUT_keys = Arrays.asList(new String[] {
			"TARGETSHARETYPE", "ERRORDETAIL", "LARGEBUYFLAG", "RAISEINTEREST",
			"FEECALCULATOR", "SHAREREGISTERDATE", "RATIONPROTOCOLNO",
			"BEGINDATEOFPERIODICSUBS", "ENDDATEOFPERIODICSUBS",
			"SENDDAYOFPERIODICSUBS", "BROKER", "SALESPROMOTION",
			"ACCEPTMETHOD", "FORCEREDEMPTIONTYPE", "ALTERNATIONDATE",
			"TAKEINCOMEFLAG", "PURPOSEOFPESUBS", "FREQUENCYOFPESUBS",
			"PERIODSUBTIMEUNIT", "BATCHNUMOFPESUBS", "CAPITALMODE",
			"DETAILCAPTICALMODE", "BACKENLOADDISCOUNT", "COMBINENUM",
			"REFUNDAMOUNT", "SALEPERCENT", "MANAGERREALRATIO", "CHANGEFEE",
			"RECUPERATEFEE", "ACHIEVEMENTPAY", "ACHIEVEMENTCOMPEN",
			"SHARESADJUSTMENTFLAG", "UNDISTRIBUTEMONETARYINCOME",
			"UNDISTRIBUTEMONETARYINCOMEFLAG", "BREACHFEE",
			"BREACHFEEBACKTOFUND", "PUNISHFEE", "TRADINGMETHOD",
			"CHANGEAGENCYFEE", "RECUPERATEAGENCYFEE", "APPSHEETSERIALNO",
			"TRANSACTIONCFMDATE", "CURRENCYTYPE", "CONFIRMEDVOL",
			"CONFIRMEDAMOUNT", "FUNDCODE", "LARGEREDEMPTIONFLAG",
			"TRANSACTIONDATE", "TRANSACTIONTIME", "RETURNCODE",
			"TRANSACTIONACCOUNTID", "DISTRIBUTORCODE", "APPLICATIONVOL",
			"APPLICATIONAMOUNT", "BUSINESSCODE", "TAACCOUNTID",
			"BUSINESSFINISHFLAG", "DISCOUNTRATEOFCOMMISSION", "DEPOSITACCT",
			"REGIONCODE", "DOWNLOADDATE", "CHARGE", "AGENCYFEE", "NAV",
			"BRANCHCODE", "ORIGINALAPPSHEETNO", "ORIGINALSUBSDATE",
			"OTHERFEE1", "INDIVIDUALORINSTITUTION", "REDEMPTIONDATEINADVANCE",
			"STAMPDUTY", "VALIDPERIOD", "RATEFEE", "TOTALBACKENDLOAD",
			"SPECIFICATION", "DATEOFPERIODICSUBS", "TARGETDISTRIBUTORCODE",
			"TARGETBRANCHCODE", "TARGETTRANSACTIONACCOUNTID",
			"TARGETREGIONCODE", "TRANSFERDIRECTION", "DEFDIVIDENDMETHOD",
			"DIVIDENDRATIO", "INTEREST", "VOLUMEBYINTEREST", "INTERESTTAX",
			"TRADINGPRICE", "FREEZINGDEADLINE", "VARIETYCODEOFPERIODICSUBS",
			"SERIALNOOFPERIODICSUBS", "RATIONTYPE", "TARGETTAACCOUNTID",
			"TARGETREGISTRARCODE", "NETNO", "CUSTOMERNO", "FROZENCAUSE", "TAX",
			"TARGETNAV", "TARGETFUNDPRICE", "CFMVOLOFTARGETFUND", "MINFEE",
			"OTHERFEE2", "ORIGINALAPPDATE", "TRANSFERFEE", "FROMTAFLAG",
			"SHARECLASS", "DETAILFLAG", "REDEMPTIONINADVANCEFLAG",
			"FROZENMETHOD", "ORIGINALCFMDATE", "REDEMPTIONREASON",
			"CODEOFTARGETFUND", "TOTALTRANSFEE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_05_OUT_keys = Arrays.asList(new String[] {
			"AVAILABLEVOL", "TOTALVOLOFDISTRIBUTORINTA", "TRANSACTIONCFMDATE",
			"FUNDCODE", "TRANSACTIONACCOUNTID", "DISTRIBUTORCODE",
			"TAACCOUNTID", "TOTALFROZENVOL", "BRANCHCODE", "TOTALBACKENDLOAD",
			"SHARECLASS", "DETAILFLAG", "ACCOUNTSTATUS", "SHAREREGISTERDATE",
			"UNDISTRIBUTEMONETARYINCOME", "UNDISTRIBUTEMONETARYINCOMEFLAG",
			"GUARANTEEDAMOUNT", "SOURCETYPE", "DEFDIVIDENDMETHOD",
			"FSALE_ORG_ID" });

	public static List<String> T_PD_I_06_OUT_keys = Arrays.asList(new String[] {
			"BASISFORCALCULATINGDIVIDEND", "TRANSACTIONCFMDATE",
			"CURRENCYTYPE", "VOLOFDIVIDENDFORREINVESTMENT", "DIVIDENTDATE",
			"DIVIDENDAMOUNT", "XRDATE", "CONFIRMEDAMOUNT", "FUNDCODE",
			"REGISTRATIONDATE", "RETURNCODE", "TRANSACTIONACCOUNTID",
			"DISTRIBUTORCODE", "BUSINESSCODE", "TAACCOUNTID",
			"DIVIDENDPERUNIT", "DEFDIVIDENDMETHOD", "DEPOSITACCT",
			"REGIONCODE", "DOWNLOADDATE", "CHARGE", "AGENCYFEE",
			"TOTALFROZENVOL", "NAV", "BRANCHCODE", "OTHERFEE1", "OTHERFEE2",
			"INDIVIDUALORINSTITUTION", "DIVIDENDRATIO", "TASERIALNO",
			"STAMPDUTY", "FROZENBALANCE", "TRANSFERFEE", "SHARECLASS",
			"FEECALCULATOR", "DRAWBONUSUNIT", "FROZENSHARESFORREINVEST",
			"DIVIDENDTYPE", "ORIGINALAPPSHEETNO", "ACHIEVEMENTPAY",
			"ACHIEVEMENTCOMPEN", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_07_OUT_keys = Arrays.asList(new String[] {
			"FUNDSERVERTEL", "FUNDINTERNETADDRESS", "FUNDNAME", "TOTALFUNDVOL",
			"FUNDCODE", "FUNDSTATUS", "NAV", "UPDATEDATE", "NETVALUETYPE",
			"ACCUMULATIVENAV", "CONVERTSTATUS", "PERIODICSTATUS",
			"TRANSFERAGENCYSTATUS", "FUNDSIZE", "CURRENCYTYPE", "ANNOUNCFLAG",
			"DEFDIVIDENDMETHOD", "INSTAPPSUBSAMNT", "INSTAPPSUBSVOL",
			"MINAMOUNTBYINST", "MINVOLBYINST", "CUSTODIANCODE",
			"AMOUNTOFPERIODICSUBS", "DATEOFPERIODICSUBS", "MAXREDEMPTIONVOL",
			"MINACCOUNTBALANCE", "IPOSTARTDATE", "IPOENDDATE",
			"FUNDMANAGERCODE", "INDIAPPSUBSVOL", "INDIAPPSUBSAMOUNT",
			"MINSUBSVOLBYINDI", "MINSUBSAMOUNTBYINDI", "REGISTRARCODE",
			"FUNDSPONSOR", "TRADINGPRICE", "FACEVALUE", "DIVIDENTDATE",
			"REGISTRATIONDATE", "XRDATE", "MAXSUBSVOLBYINDI",
			"MAXSUBSAMOUNTBYINDI", "MAXSUBSVOLBYINST", "MAXSUBSAMOUNTBYINST",
			"UNITSUBSVOLBYINDI", "UNITSUBSAMOUNTBYINDI", "UNITSUBSVOLBYINST",
			"UNITSUBSAMOUNTBYINST", "MINBIDSAMOUNTBYINDI",
			"MINBIDSAMOUNTBYINST", "MINAPPBIDSAMOUNTBYINDI",
			"MINAPPBIDSAMOUNTBYINST", "MINREDEMPTIONVOL", "MININTERCONVERTVOL",
			"ISSUETYPEBYINDI", "ISSUETYPEBYINST", "SUBSTYPE", "COLLECTFEETYPE",
			"NEXTTRADEDATE", "VALUELINE", "TOTALDIVIDENT", "FUNDINCOME",
			"FUNDINCOMEFLAG", "YIELD", "YIELDFLAG", "GUARANTEEDNAV",
			"FUNDYEARINCOMERATE", "FUNDYEARINCOMERATEFLAG", "INDIMAXPURCHASE",
			"INSTMAXPURCHASE", "INDIDAYMAXSUMBUY", "INSTDAYMAXSUMBUY",
			"INDIDAYMAXSUMREDEEM", "INSTDAYMAXSUMREDEEM", "INDIMAXREDEEM",
			"INSTMAXREDEEM", "FUNDDAYINCOMEFLAG", "FUNDDAYINCOME",
			"ALLOWBREACHREDEMPT", "FUNDTYPE", "FUNDTYPENAME", "REGISTRARNAME",
			"FUNDMANAGERNAME", "DISTRIBUTORCODE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_08_OUT_keys = Arrays.asList(new String[] {
			"ANNCONTENT", "ANNOUNCEMENTNO", "ANNOUNCEMENTDATE",
			"ANNOUNCEMENTTYPE", "LENGTHOFANNOUNCEMENT", "ANNOUNCEMENTTITLE",
			"DISTRIBUTORCODE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_09_OUT_keys = Arrays.asList(new String[] {
			"DIVIDENTDATE", "TOTALDIVIDENDAMOUNT", "TOTALDIVIDENDINDEED",
			"TOTALFEEFORDIVIDEND", "FUNDCODE", "TOTALREINVESTMENTDIVIDEND",
			"DISTRIBUTORCODE", "DOCUMENTSENDDATE", "TAX", "TVRDQUTY",
			"FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_10_OUT_keys = Arrays.asList(new String[] {
			"TOTALSUBSAMNT", "TOTALSUBSCHARGE", "TOTALSUBSVOL", "FUNDCODE",
			"TOTALREDEMPTIONAMOUNT", "TOTALFEEOFREDEMPTION",
			"TOTALREDEMPTIONVOL", "DISTRIBUTORCODE", "AMNTREINBURSED",
			"TOTALVOLOFDISTRIBUTORINTA", "VOLOFDIVIDENDFORREINVESTMENT",
			"DIVIDENDAMOUNT", "TOTALDIVIDENDAMOUNT", "TOTALFEEFORDIVIDEND",
			"BACKAMOUNTBYINVALID", "OTHERFEE2", "OTHERFEE3",
			"TOTALREINVESTMENTDIVIDEND", "BACKAMOUNTBYEXCESS", "TAX",
			"AGGREGATIONDATE", "TRAILCOMMISSION", "TOTALFRONTENDFEE",
			"TOTALBACKENDLOAD", "SALERNETRECEIVABLEAMOUNT",
			"SALERNETPAYABLEAMOUNT", "SALERTOTALFEE", "SALERBUYFEE",
			"SALERBIDFEE", "FUNDTOTALFEE", "RAISETOTALAMOUNT",
			"ACCUMULATIVETOTALRAISEAMOUNT", "RAISEINTEREST", "SALERRAISEFEE",
			"CONVERSIONINAMOUNT", "CONVERTINGTOAMOUNT", "SALEREXCHANGEFEE",
			"BIDTAX", "REDEMPTIONTAX", "INDIVIDUALCAPITALGAINTAX",
			"INSTITUTECAPITALGAINTAX", "INDIVIDUALINCOMETAX",
			"INSTITUTEINCOMETAX", "SALERREINVESTMENTFEE", "SUBFEERETTA",
			"REDEMFEERETTA", "TOTALTRANSINAMOUNT", "TOTALFEEOFTRANSINAMOUNT",
			"TOTALTRANSINVOL", "TOTALTRANSOUTAMOUNT",
			"TOTALFEEOFTRANSOUTAMOUNT", "TOTALTRANSOUTVOL", "BIDTRADE",
			"REDEEMTRADE", "FREEZETOTAL", "MANAGERCODE", "NETBIDTOTALAMOUNT",
			"NETREDEEMTOTALAMOUNT", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_11_OUT_keys = Arrays.asList(new String[] {
			"FUNDCODE", "DISTRIBUTORCODE", "BUSINESSCODE", "AOTBBTOFD",
			"AGGREGATIONDATE", "TOTALSUCCESSFULVOL", "TOTALSUCCESSFULAMOUNT",
			"FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_12_OUT_keys = Arrays.asList(new String[] {
			"FUNDCODE", "DISTRIBUTORCODE", "BUSINESSCODE", "AOTBBTOFD",
			"AGGREGATIONDATE", "TOTALFAILINGVOL", "TOTALSUCCESSFULVOL",
			"TOTALFAILINGAMOUNT", "TOTALSUCCESSFULAMOUNT",
			"TOTALFAILINGDEALINGNUM", "TOTALSUCCESSFULDEALINGNUM",
			"FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_13_IN_keys = Arrays.asList(new String[] {
			"FUNDCODE", "DISTRIBUTORCODE", "BUSINESSCODE", "TACODE",
			"AGGREGATIONBYTYPE", "AGGREGATIONDATE", "TOTALSUCCESSFULVOL",
			"TOTALSUCCESSFULAMOUNT", "ORGID" });

	public static List<String> T_PD_I_21_OUT_keys = Arrays.asList(new String[] {
			"SEATCODE", "DISTRIBUTORCODE", "DISTRIBUTORNAME",
			"TRANSFERPERMITFLAG", "DOWNLOADDATE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_23_IN_keys = Arrays.asList(new String[] {
			"APPSHEETSERIALNO", "CURRENCYTYPE", "TAACCOUNTID",
			"TRANSACTIONACCOUNTID", "SECURITIESACCOUNTID", "SEATCODE",
			"INVESTORNAME", "INDIVIDUALORINSTITUTION", "CERTIFICATETYPE",
			"CERTIFICATENO", "TRANSACTIONDATE", "TRANSACTIONTIME",
			"BUSINESSCODE", "FUNDCODE", "APPLICATIONVOL", "DISTRIBUTORCODE",
			"BRANCHCODE", "DEPOSITACCT", "NETNO", "REGIONCODE", "TELNO",
			"MOBILETELNO", "ADDRESS", "POSTCODE", "EMAILADDRESS",
			"TRANSACTORCERTNO", "TRANSACTORCERTTYPE", "TRANSACTORNAME",
			"INVESTORSBIRTHDAY", "EDUCATIONLEVEL", "FAXNO", "VOCATIONCODE",
			"HOMETELNO", "ANNUALINCOME", "OFFICETELNO", "ACCOUNTABBR", "SEX",
			"APPLICATIONAMOUNT", "MINORFLAG", "DELIVERTYPE",
			"TRANSACTORIDTYPE", "SHARECLASS", "DELIVERWAY",
			"TARGETDISTRIBUTORCODE", "TARGETBRANCHCODE",
			"TARGETTRANSACTIONACCOUNTID", "TARGETREGIONCODE", "ORGID" });

	public static List<String> T_PD_I_24_OUT_keys = Arrays.asList(new String[] {
			"APPSHEETSERIALNO", "CURRENCYTYPE", "TAACCOUNTID",
			"TRANSACTIONACCOUNTID", "SECURITIESACCOUNTID", "SEATCODE",
			"TRANSACTIONDATE", "TRANSACTIONTIME", "BUSINESSCODE", "FUNDCODE",
			"APPLICATIONVOL", "CONFIRMEDVOL", "DISTRIBUTORCODE",
			"TRANSACTIONCFMDATE", "DOWNLOADDATE", "BRANCHCODE", "NETNO",
			"REGIONCODE", "TASERIALNO", "RETURNCODE", "FROMTAFLAG",
			"SHARECLASS", "ERRORDETAIL", "CHARGE", "AGENCYFEE", "NAV",
			"OTHERFEE1", "TOTALBACKENDLOAD", "RATEFEE", "TRANSFERFEE",
			"ORIGINALCFMDATE", "FUNDCORPCODE", "POINTSTYPE", "POINTSSTATUS",
			"POINTS", "ALTERNATIONDATE", "TARGETDISTRIBUTORCODE",
			"TARGETBRANCHCODE", "TARGETTRANSACTIONACCOUNTID",
			"TARGETREGIONCODE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_25_OUT_keys = Arrays.asList(new String[] {
			"TRANSACTIONDATE", "TRANSACTIONCFMDATE",
			"CURRENCYTYPE", "EXCHANGEFLAG", "INSTACCOUNT", "FUNDCODE",
			"DISTRIBUTORCODE", "SEATCODE", "BRANCHCODE", "BUSINESSCODE",
			"CAPITALTYPE", "CONFIRMEDAMOUNT", "RECEORPAYFLAG", "CALCULATEDATE",
			"PAYDATE", "DETAILFLAG", "DOWNLOADDATE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_ADJUSTSHARE_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FINCREASE_SHARE", "FDECREASE_SHARE",
					"FINCREASE_UE", "FDECREASE_UE", "FSHARE_BALANCE",
					"FUNPAID_EARNINGS", "FCHARGETYPE", "FSHARE_LEVEL",
					"FINCREASE_AMT", "FDECREASE_AMT", "ORGID", "FMINUS_VOL" });

	public static List<String> T_PD_I_ALLOT_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FSUBAMT", "FACKAMT", "FFEE",
					"FSTAMPDUTY", "FTRANSFERFEE", "FACKQUTY", "FCHARGETYPE",
					"FSHARE_LEVEL", "ORGID" });

	public static List<String> T_PD_I_BONUS_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FDIVIDEND", "FTAX", "FSTAMPDUTY",
					"FCASH", "FFROZENBALANCE", "FREALDIVIDEND", "FFEE",
					"FREPRICE", "FDIVQUTY", "FCHARGETYPE", "FSHARE_LEVEL",
					"FACHIEVEMENTPAY", "FTAIL", "ORGID" });

	public static List<String> T_PD_I_C1_OUT_keys = Arrays.asList(new String[] {
			"SHARECLASS", "FUNDNAME", "FUNDNAMEABBR", "TOTALFUNDVOL",
			"FUNDTYPE", "FUNDTYPENAME", "ISGUARANTEEDFUND", "ISLOFFUND",
			"ISQDIIFUND", "ISETFFUND", "REDEEMFEEBACKRATIO",
			"DEFDIVIDENDMETHOD", "REDEMPTIONSEQUENCE", "BUYUPPERAMOUNT",
			"COVERTINUPPERAMOUNT", "PERIODSUBUPPERAMOUNT", "INSTAPPSUBSAMNT",
			"INSTAPPSUBSVOL", "MINAMOUNTBYINST", "MINVOLBYINST",
			"CURRENCYTYPE", "CUSTODIANCODE", "AMOUNTOFPERIODICSUBS",
			"DATEOFPERIODICSUBS", "MAXREDEMPTIONVOL", "MINACCOUNTBALANCE",
			"IPOSTARTDATE", "IPOENDDATE", "FUNDESTABLISHDATE",
			"FUNDMANAGERCODE", "INDIAPPSUBSVOL", "INDIAPPSUBSAMOUNT",
			"MINSUBSVOLBYINDI", "MINSUBSAMOUNTBYINDI", "REGISTRARCODE",
			"FUNDSIZE", "EXCHANGEFLAG", "FUNDSPONSOR", "FACEVALUE",
			"MAXSUBSVOLBYINDI", "MAXSUBSAMOUNTBYINDI", "MAXSUBSVOLBYINST",
			"MAXSUBSAMOUNTBYINST", "UNITSUBSVOLBYINDI", "UNITSUBSAMOUNTBYINDI",
			"UNITSUBSVOLBYINST", "UNITSUBSAMOUNTBYINST", "MINBIDSAMOUNTBYINDI",
			"MINBIDSAMOUNTBYINST", "MINAPPBIDSAMOUNTBYINDI",
			"MINAPPBIDSAMOUNTBYINST", "MINREDEMPTIONVOL", "MININTERCONVERTVOL",
			"ISSUETYPEBYINDI", "ISSUETYPEBYINST", "SUBSTYPE", "COLLECTFEETYPE",
			"INDIMAXPURCHASE", "INSTMAXPURCHASE", "INDIDAYMAXSUMBUY",
			"INSTDAYMAXSUMBUY", "INDIDAYMAXSUMREDEEM", "INSTDAYMAXSUMREDEEM",
			"INDIMAXREDEEM", "INSTMAXREDEEM", "REGISTRARNAME",
			"FUNDMANAGERNAME", "FUNDSERVERTEL", "FUNDINTERNETADDRESS",
			"SPECIFICATION", "WHOLEFLAG", "MODIFYWAY", "DISTRIBUTORCODE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_C2_OUT_keys = Arrays.asList(new String[] {
			"FUNDCODE", "SHARECLASS", "DISTRIBUTORCODE",
			"BRANCHCODE", "ISDISCOUNT", "BUYPAYPERIOD", "REDEMPTIONPAYPERIOD",
			"CONVERSIONPAYPERIOD", "SUBPAYBACKPERIOD", "DIVIDENDPAYPERIOD",
			"CHARGEPAYMETHOD", "WHOLEFLAG", "MODIFYWAY", "OPERATEDATE",
			"DOWNLOADDATE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_C3_OUT_keys = Arrays.asList(new String[] {
			"FUNDCODE", "SHARECLASS", "VOLLOWERLIMIT", "VOLUPPERLIMIT",
			"DAYSLOWERLIMIT", "CODEOFTARGETFUND", "TARGETSHARETYPE",
			"INDIVIDUALORINSTITUTION", "REGISTRARCODE", "TARGETREGISTRARCODE",
			"WHOLEFLAG", "MODIFYWAY","DISTRIBUTORCODE", "FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_C4_OUT_keys = Arrays.asList(new String[] {
			"FUNDCODE", "SHARECLASS", "REGISTRATIONDATE",
			"DIVIDENTDATE", "XRDATE", "DIVIDENDPERUNIT", "DRAWBONUSUNIT",
			"XRVALUE", "XRVALUEFLAG", "XRTYPE", "SPECIFICATION", "WHOLEFLAG",
			"MODIFYWAY","TACODE", "BATCH_NO",
			"DISTRIBUTORCODE", "FSALE_ORG_ID", "ORGID", "SENDER", "RECEIVER",
			"BATCHNO" });

	public static List<String> T_PD_I_C5_OUT_keys = Arrays
			.asList(new String[] { "FUNDCODE", "SHARECLASS",
					"CODEOFTARGETFUND", "TARGETSHARETYPE", "DISTRIBUTORCODE",
					"BRANCHCODE", "BUSINESSCODE", "CAPITALTYPE",
					"INDIVIDUALORINSTITUTION", "GETFEERATEMETHOD",
					"CONSTANTFEE", "VOLLOWERLIMIT", "VOLUPPERLIMIT",
					"AMOUNTLOWERLIMIT", "AMOUNTUPPERLIMIT", "DAYSLOWERLIMIT",
					"DAYSUPPERLIMIT", "MAXFEE", "MINFEE", "RATEFEE",
					"FEERATEFLAG", "COMPAREPROPORTION", "COMPARECAPITALTYPE",
					"WHOLEFLAG", "MODIFYWAY", "OPERATEDATE",
					"FSALE_ORG_ID", "ORGID" });

	public static List<String> T_PD_I_CHANGEAGENCY_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FOUT_ACKQUTY", "FIN_ACKQUTY",
					"FOUT_INCOME", "FIN_INCOME", "FCHARGETYPE", "FSHARE_LEVEL",
					"ORGID" });

	public static List<String> T_PD_I_INCOME_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FNOINCOME",
					"FNOWINCOME", "FUNPAID_INCOME", "FSHARE_LEVEL",
					"FCANCE_QUTY", "ORGID" });

	public static List<String> T_PD_I_NAV_IN_keys = Arrays.asList(new String[] {
			"FFD_NET_DATE", "FFUNDNAME", "FFUNDID", "FFD_TOTAL_NET",
			"FFD_TOTAL_SHARE", "FFD_UNIT_NET", "FFD_INCOME", "FQUTOINCOMERATE",
			"FINCOMERATE", "FSALEFEE", "FFD_SUM_NET", "FNET_GROWTHRATE",
			"FMGRFEE", "FQUARTERRATE", "FTWOINCOME", "FNDEPOSIT_DAYOFYIELD",
			"FFD_SHARE_LEVEL", "FTOTAL_ASSET_NET", "ORGID" });

	public static List<String> T_PD_I_NAV_OUT_keys = Arrays
			.asList(new String[] { "FNAV_CODE", "FFD_NET_DATE", "FFUNDNAME",
					"FFUNDID", "FFD_TOTAL_NET", "FFD_TOTAL_SHARE",
					"FFD_UNIT_NET", "FFD_INCOME", "FQUTOINCOMERATE",
					"FINCOMERATE", "FSALEFEE", "FFD_SUM_NET",
					"FNET_GROWTHRATE", "FMGRFEE", "FQUARTERRATE", "FTWOINCOME",
					"FNDEPOSIT_DAYOFYIELD", "FFD_SHARE_LEVEL",
					"FTOTAL_ASSET_NET", "ORGID" });

	public static List<String> T_PD_I_NAVADD_IN_keys = Arrays
			.asList(new String[] { "FFD_NET_DATE", "FFUNDNAME", "FFUNDID",
					"FFD_TOTAL_NET", "FFD_TOTAL_SHARE", "FFD_UNIT_NET",
					"FFD_INCOME", "FQUTOINCOMERATE", "FINCOMERATE", "FSALEFEE",
					"FFD_SUM_NET", "FNET_GROWTHRATE", "FMGRFEE",
					"FQUARTERRATE", "FTWOINCOME", "FNDEPOSIT_DAYOFYIELD",
					"FFD_SHARE_LEVEL", "FTOTAL_ASSET_NET", "ORGID", "SENDER",
					"RECEIVER", "BATCHNO" });

	public static List<String> T_PD_I_NAVADD_OUT_keys = Arrays
			.asList(new String[] { "FFD_NET_DATE", "FFUNDNAME", "FFUNDID",
					"FFD_TOTAL_NET", "FFD_TOTAL_SHARE", "FFD_UNIT_NET",
					"FFD_INCOME", "FQUTOINCOMERATE", "FINCOMERATE", "FSALEFEE",
					"FFD_SUM_NET", "FNET_GROWTHRATE", "FMGRFEE",
					"FQUARTERRATE", "FTWOINCOME", "FNDEPOSIT_DAYOFYIELD",
					"FFD_SHARE_LEVEL", "FTOTAL_ASSET_NET", "ORGID" });

	public static List<String> T_PD_I_REDEEM_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FACKQUTY", "FMARKAMT", "FFEEREDM",
					"FSTAMPDUTY", "FTRANSFERFEE", "FFEEBID", "FOTHERFEE",
					"FOTHERFEE1", "FACKAMT", "FFROZENBALANCE", "FCHARGETYPE",
					"FSHARE_LEVEL", "FFUNDFEE", "FACHIEVEMENTPAY", "ORGID" });

	public static List<String> T_PD_I_SUB_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FSUBFLAG", "FSUBAMT", "FACKAMT",
					"FTRANSACTION_COST", "FSTAMPDUTY", "FTRANSFERFEE",
					"FREFUND_AMOUNT", "FACKQUTY", "FCHARGETYPE",
					"FSHARE_LEVEL", "FNDER", "FCEIVER", "FTCHNO", "FGID", "FD",
					"ORGID" });

	public static List<String> T_PD_I_SWITCHIN_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FACKAMT", "FFEE", "FSTAMPDUTY",
					"FTRANSFERFEE", "FACKQUTY", "FCHARGETYPE", "FSHARE_LEVEL",
					"ORGID" });

	public static List<String> T_PD_I_SWITCHOUT_OUT_keys = Arrays
			.asList(new String[] { "FAPDT", "FPD_FN", "FFUNDID", "FSEATNO",
					"FSALE_ORG_NAME", "FACKQUTY", "FACKAMT", "FFEE",
					"FSTAMPDUTY", "FTRANSFERFEE", "FRECUPERATEFEE", "FFUNDFEE",
					"FTRANSFER_AMOUNT", "FCHARGETYPE", "FSHARE_LEVEL", "ORGID",
					"FOTHER_FEE" });

	// FIXME:该表，业绩报酬流水未找到,以下字段从数据库中抓取
	public static List<String> T_TA_ACHIEVEMENTPAYBLOTTER_keys = Arrays
			.asList(new String[] { "FAPPNO", "FSEATNO", "FFUNDACCT", "FCUSTNO",
					"FAPKIND", "FPD_CODE", "FCHARGE_TYPE", "FACKDATE",
					"FACKQUTY", "FACKAMT", "FACHIEVEMENTPAY", "FBREACHFEE",
					"FAPPLYST", "FACHIEVETYPE", "FMINUSQUTY", 
					"FCHECKED","FCLEARDT" });

	public static List<String> T_TA_ACHIEVEPAYBLOTTERDETAIL_keys = Arrays
			.asList(new String[] { "FAPPNO", "FORIGANLACKNO", "FSEATNO",
					"FFUNDACCT", "FCUSTNO", "FAPKIND", "FPD_CODE",
					"FCHARGE_TYPE", "FACKDT", "FACKQUTY", "FACKAMT",
					"FACHIEVEMENTPAY", "FBREACHFEE", "FAPPLYST", "FTAIL",
					"FACHIEVETYPE", "FMINUSQUTY", "FOLDACKNO",
					"FOLDNAV", "FNAV", "FSUMOFNAV", "FCURRATIO", "FYEARRATIO",
					"FPROTECTRATIO", "FMANAGERFARE", "FPROFITBACKFARE",
					"FDEDUCTBALANCE", "FFACTDEDUCTSHARES", "FINCOMEAMT",
					"FHOLDINGDAYS",	"FCLEARDT" });

	public static List<String> T_TA_ACKFDACBLOTTER_keys = Arrays
			.asList(new String[] { "FAPPNO", "FSEATNO", "FNETPOINT",
					"FCUSTTYPE", "FCUSTNO", "FAPKIND", "FACKDT", "FSETTLEDATE",
					"FFUNDACCT", "FWARRANT", "FINVTYPE", "FINVNAME", "FIDTYPE",
					"FIDNO", "FACCOUNTABBR", "FMELONMD", "FMULTIACCTFLAG",
					"FFROZENCAUSE", "FFREEZINGDEADLINE", "FTRANSST",
					"FAPPLYST", "FBROADCASTFLAG", "FRETCODE",
					"FSUMMARY", "FCUSTODIANNETNO", "FCUSTIDVALID",
					"FDISTRIBUTORCODE", "FAPDT", "FAPTM", "FFROMTAFLAG",
					"FOCUSTNO", "FTACUSTOMERNO", "FERRORDETAIL",
					"FFROMNETPOINT" });

	public static List<String> T_TA_ACKTRADEBLOTTER_keys = Arrays
			.asList(new String[] { "FAPPNO", "FSEATNO", "FORIGINALAPPNO",
					"FNETPOINT", "FREGIONCODE", "FFUNDACCT", "FINVTP",
					"FCUSTNO", "FAPKIND", "FFUNDID", "FSUBAMT", "FSUBQUTY",
					"FCURRENCYTYPE", "FCOMMRO", "FBOOKING", "FVALIDAYS",
					"FLARGEREDEEMFLAG", "FAPPLYNAV", "FACKNAV", "FCHARGERATE",
					"FFEE", "FAGENCYFEE", "FFEEREDM", "FFEEBID", "FTAFEE",
					"FFUNDFEE", "FTAX", "FSTAMPDUTY", "FINTEREST",
					"FINTERESTTAX", "FOTHERFEE", "FTAIL", "FLASTBAL",
					"FACKAMT", "FACKQUTY", "FBALANCE", "FAVAILABLE", "FBANKNO",
					"FCLEARACCT", "FOSEATNO", "FOFUNDACCT", "FOCUSTNO",
					"FOFUNDID", "FMELONMD", "FDIVIDENDRATIO",
					"FFREEZINGDEADLINE", "FFROZENCAUSE", "FDATEOFPERIODICSUBS",
					"FPLANID", "FCONTRACTNO", "FORIGINALAPPDATE", "FAPDT",
					"FAPTM", "FACKDT", "FSNTM", "FSETTLEDATE", "FNAVDT",
					"FNAV", "FMINTDH", "FUNFROZENBALANCE", "FFROZENSHARES",
					"FFROZENBALANCE", "FCHARGETYPE", "FTRANSST",
					"FAPPLYST", "FBROADCASTFLAG", "FRETCODE",
					"FSUMMARY", "FCUSTODIANNETNO", "FOCUSTODIANNETNO",
					"FOCHARGETYPE", "FACHIEVEMENTPAY", "FBREACHFEE",
					"FFROMNETPOINT", "FMGRID", "FACCPTMD", "FINVGROUPNO",
					"FDETAILFLAG", "FVARIETYCODEOFPERIODICSUBS", "FRATIONTYPE",
					"FTACUSTOMERNO", "FSERIALNOOFPERIODICSUBS",
					"FRATIONPROTOCOLNO", "FBEGINDATEOFPERIODICSUBS",
					"FENDDATEOFPERIODICSUBS", "FSENDDAYOFPERIODICSUBS",
					"FSALESPROMOTION", "FFORCEREDEMPTIONTYPE",
					"FALTERNATIONDATE", "FTAKEINCOMEFLAG", "FPURPOSEOFPESUBS",
					"FFREQUENCYOFPESUBS", "FBATCHNUMOFPESUBS", "FCAPITALMODE",
					"FDETAILCAPTICALMODE", "FBACKENLOADDISCOUNT",
					"FREFUNDAMOUNT", "FSALEPERCENT", "FMANAGERREALRATIO",
					"FCHANGEFEE", "FRECUPERATEFEE", "FACHIEVEMENTCOMPEN",
					"FSHARESADJUSTMENTFLAG", "FGENERALTASERIALNO",
					"FUNDISTRIBUTEMONETARYINCOME",
					"FUNDISTRIBUTEMONETARYINCOMEFL", "FBREACHFEEBACKTOFUND",
					"FPUNISHFEE", "FCHANGEAGENCYFEE", "FRECUPERATEAGENCYFEE",
					"FERRORDETAIL", "FTOTALTRANSFEE", "FREDEMPTIONREASON",
					"FORIGINALCFMDATE", "FFROZENMETHOD",
					"FREDEMPTIONINADVANCEFLAG", "FFROMTAFLAG", "FTRANSFERFEE",
					"FOTHERFEE2", "FMINFEE", "FCFMVOLOFTARGETFUND",
					"FTARGETFUNDPRICE", "FTARGETNAV", "FTRADINGPRICE",
					"FTRANSFERDIRECTION", "FTARGETREGIONCODE",
					"FTARGETBRANCHCODE", "FVOLUMEBYINTEREST",
					"FTOTALBACKENDLOAD", "FRATEFEE", "FORIGINALSUBSDATE",
					"FLARGEREDEMPTIONFLAG", "FFEECALCULATOR", "FDRAWBONUSUNIT",
					"FFROZENSHARESFORREINVEST", "FDIVIDENDTYPE", "FXRDATE",
					"FREGISTRATIONDATE", "FDIVIDENDPERUNIT", "FTOTALFROZENVOL",
					"FLARGEBUYFLAG", "FRAISEINTEREST", "FSHAREREGISTERDATE",
					"FPERIODSUBTIMEUNIT", "FOTHERFEE1", "FFORCEREDTYPE",
					"FL_SERIALNO", "FINCOMEAMT", "FDATA_SOURCE", "FSHARE_TYPE",
					"FINCOME", "FTRADEOFENDED", "FAMTOFEND", "FGDINCOME" });

//	public static List<String> T_TA_APPNOACKNOREF_keys = Arrays
//			.asList(new String[] { "FAPPNO", "FCLEARDT", "FAPKIND" });

	public static List<String> T_TA_BALCONS_keys = Arrays.asList(new String[] {
			"FAPPNO", "FFUNDACCT", "FSEATNO", "FCUSTNO", "FPD_CODE", "FAPKIND",
			"FACKDT", "FPD_CODE_OUT", "FNETQUTY", "FAVAILABLE", "FFROZEN",
			"FABNMFROZEN", "FORGQUTY", "FACKAMT", "FCOMMRO", "FNAV", "FBALST",
			"FCHARGETYPE", "FFEEID", "FPLANID", "FCONTRACTNO", "FLASTMODIDT",
			"FCUSTODIANNETNO", "FINCOMEAMT", "FINCOMEDAY", "FINCOMENEXT",
			"FTAIL", "FTAILORDER", "FPREDISAMT", "FSUMDISAMT", "FAUTODISAMT",
			"FALLOWREDEMPTDATE", "FCYCLEBEGINDT", "FCLEARDT", "FVALIDATED",
			"FSHARE_TYPE", "FISIN", "FPID", "FCHGQUTY" });

	public static List<String> T_TA_BALCONSBLOTTER_keys = Arrays
			.asList(new String[] { "FAPPNO", "FFUNDACCT", "FSEATNO",
					"FCUSTNO", "FPD_CODE", "FAPKIND", "FACKDT", "FPD_CODE_OUT",
					"FNETQUTY", "FAVAILABLE", "FFROZEN", "FABNMFROZEN",
					"FORGQUTY", "FACKAMT", "FCOMMRO", "FNAV", "FBALST",
					"FCHARGETYPE", "FFEEID", "FPLANID", "FCONTRACTNO",
					"FCUSTODIANNETNO", "FINCOMEAMT",
					"FINCOMEDAY", "FINCOMENEXT", "FTAIL", "FTAILORDER",
					"FPREDISAMT", "FSUMDISAMT", "FAUTODISAMT",
					"FALLOWREDEMPTDATE", "FCYCLEBEGINDT", "FCLEARDT",
					"FVALIDATED", "FSHARE_TYPE", "FISIN", "FPID", "FCHGQUTY" });
	// TODO:数据库里不存在这张表
	// public static List<String> T_TA_DEFAULTPARAM_keys = Arrays
	// .asList(new String[] { "FDV_TYPE", "FDV_CODE", "FDV_VALUE",
	// "FJAVA_TYPE", "FDESC", "FSPARE0", "FSPARE1", "FSPARE2",
	// "FSPARE3", "FSPARE4", "FCREATOR_ID", "FCREATE_TIME",
	// "FLAST_EDIT_TIME", "FLAST_EDITOR_ID", "FDELETED",
	// "FDELETE_USER_ID", "FMARK_DELETED_TIME", "FCHECKED",
	// "FCHECKER_ID", "FCHECK_TIME", "FSTART_TIME", "FEND_TIME" });

	public static List<String> T_TA_FUNDBALANCE_keys = Arrays
			.asList(new String[] { "FFUNDACCT", "FSEATNO", "FPD_CODE",
					"FCUSTNO", "FINVNAME", "FBANKNO", "FCLEARACCT", "FINVTYPE",
					"FBALANCE", "FAVAILABLE", "FFROZEN", "FHFROZEN",
					"FABNMFROZEN", "FCRC_BALANCE", "FCRC_AVAILABLE",
					"FLASTMODIDT", "FSUMBALANCE", "FSUMAMT", "FAVGCOST",
					"FCUSTODIANNETNO", "FCHARGE_TYPE", "FINCOMEAMT",
					"FINCOMEDAY", "FINCOMENEXT", "FTAIL", "FTAILORDER",
					"FPREDISAMT", "FSUMDISAMT", "FAUTODISAMT", "FSALEFEE",
					"FLASTCHGBALANCE", "FSALEFEETAIL", "FSALEFEETAILORDER",
					"FCLEARDT", "FVALIDATED" });

	public static List<String> T_TA_RIGHTSREG_keys = Arrays
			.asList(new String[] { "FPJNO", "FFUNDACCT", "FSEATNO", "FCUSTNO",
					"FPD_CODE", "FINVNAME", "FINVTYPE", "FREGQUTY",
					"FFROZENQUTY", "FREGTYPE", "FBONUSTATE", "FDIVIDEND",
					"FCASH", "FDIVQUTY", "FTAX", "FFEE", "FDIVPERUNIT",
					"FQUTYPERUNIT", "FMELONMD", "FDIVIDENDRATIO", "FREPRICE",
					"FREG_DATE", "FEXTEND_DATE", "FDEAL_DATE", "FFROZENCASH",
					"FFROZENDIVQUTY", "FTRUSTEE_CODE", "FCHARGE_TYPE",
					"FACHIEVEMENTPAY", "FREALDIVIDEND", "FTAIL",
					"FSHARE_LEVEL", "FCLEARDATE" });

	public static List<String> T_TA_RIGHTSREGDETIAL_keys = Arrays
			.asList(new String[] { "FPJNO", "FOLDBALACKNO", "FBALACKNO",
					"FACKNO1", "FACKNO2", "FACKNO3", "FACKNO4", "FACKNO5",
					"FAPKIND1", "FAPKIND2", "FAPKIND3", "FAPKIND4", "FAPKIND5",
					"FFUNDACCT", "FSEATNO", "FCUSTNO", "FPD_CODE", "FINVNAME",
					"FINVTYPE", "FREGQUTY", "FFROZENQUTY", "FMELONMD",
					"FDIVIDENDRATIO", "FREGTYPE", "FBONUSTATE", "FDIVIDEND",
					"FNREALDIVIDEND", "FCASH", "FDIVQUTY", "FTAX", "FFEE",
					"FACHIEVEMENTPAY", "FFEERATE", "FDIVPERUNIT",
					"FQUTYPERUNIT", "FREPRICE", "FCOSTING", "FDEALBEGINDT",
					"FREG_DATE", "FEXTEND_DATE", "FDEAL_DATE",
					"FCUSTODIANNETNO", "FCHARGE_TYPE", "FOLDREGQUTY",
					"FCASHACHIEVEMENTPAY", "FQUTYACHIEVEMENTPAY", "FCLEARDATE" });

	public static List<String> T_TA_SERVICECHARGEBLOTTER_keys = Arrays
			.asList(new String[] { "FCALCULATEDATE", "FPD_CODE", "FSEATNO",
					"FBALANCE", "FAMT", "FSERVICECHARGERATE", "FSERVICECHARGE" });
}
